#!/usr/bin/env bash
#transfers a file from our client to a server:
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

filePath=$1
serverIp=$2
userName=$3
sshKey=$4

if [ -z "$ssh_key" ]; then
  scp -o StrictHostKeyChecking=no "$filePath" "$userName@$serverIp:~/"
else
  scp -o StrictHostKeyChecking=no -i "$sshKey" "$filePath" "$userName@$serverIp:~/"
fi
