#!/usr/bin/env bash
# Configure your Nginx server so that "/redirect_me" is redirecting to another page

STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/S3EVrcNQj0o?si=Ot4UNWLXh6sQ4HbR; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart
